### ISSUE TITLE
Cannot Connect to Metamask 

### ISSUE THREAD

**Issue by Ed-Marcavage** [Provenance-Market/Interface01#3]
**Bug Description**

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by Provenance-Market** [comment]
Ensure you download the useDapp lib
